name: Analyse

on:
  push:
  pull_request:

jobs:
  src:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          tools: composer:v2
          coverage: none
        env:
          COMPOSER_AUTH_JSON: |
            {
              "http-basic": {
                "nova.laravel.com": {
                  "username": "${{ secrets.NOVA_3_0_USERNAME }}",
                  "password": "${{ secrets.NOVA_3_0_PASSWORD }}"
                }
              }
            }

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --prefer-dist --no-interaction --no-progress

      - name: Analyse
        run: vendor/bin/phpstan
